# Site settings
name: Timlen
title: Timlen's Blog
email: tinglenxan@gmail.com
description: ># this means to ignore newlines until "baseurl:"
     Wellcome! It's a site shares my knowledge, technology and experience.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: tinglentse
github_username: timlentse
facebook_name: timlenxan
google_plus_name: timlen

# Build settings
markdown: kramdown
